// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNSoOgJbydRojudai8V5oCK1CPKv-yYas',
    appId: '1:693497036668:web:10324d602db52f32c42ef9',
    messagingSenderId: '693497036668',
    projectId: 'blood-bank-ced6f',
    authDomain: 'blood-bank-ced6f.firebaseapp.com',
    storageBucket: 'blood-bank-ced6f.appspot.com',
    measurementId: 'G-F8NSSC8G8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOqEbMDfQQjZAd-o1fe8d811VOpV7b0hw',
    appId: '1:693497036668:android:eb48dd2c8d8ca4b0c42ef9',
    messagingSenderId: '693497036668',
    projectId: 'blood-bank-ced6f',
    storageBucket: 'blood-bank-ced6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnDBsCLxzCdZYJYIwpCMzvpF7ib9Srmqc',
    appId: '1:693497036668:ios:d8f3bba5d0553ff5c42ef9',
    messagingSenderId: '693497036668',
    projectId: 'blood-bank-ced6f',
    storageBucket: 'blood-bank-ced6f.appspot.com',
    iosBundleId: 'com.infinity.bloodBankManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnDBsCLxzCdZYJYIwpCMzvpF7ib9Srmqc',
    appId: '1:693497036668:ios:d8f3bba5d0553ff5c42ef9',
    messagingSenderId: '693497036668',
    projectId: 'blood-bank-ced6f',
    storageBucket: 'blood-bank-ced6f.appspot.com',
    iosBundleId: 'com.infinity.bloodBankManagement',
  );
}
